# Generated by Django 6.0.2 on 2026-02-20 11:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='min_stock',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
