# Generated by Django 6.0.2 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_move_is_kitchen_to_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_kitchen',
        ),
        migrations.AddField(
            model_name='staff',
            name='is_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
