# Generated by Django 6.0.2 on 2026-02-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_vendor_phone_raw_material_min_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
