# Generated by Django 6.0.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_restaurant',
        ),
    ]
