# Generated by Django 6.0.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_restaurant_is_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='tax_percent',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='esewa_merchant_id',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
