# Generated by Django 6.0.2 on 2026-02-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_country_code_restaurant_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboset',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
