# Generated by Django 6.0.2 on 2026-02-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_combo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combos/'),
        ),
    ]
