# Generated by Django 6.0.2 on 2026-03-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_rbac_and_restaurant_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulknotification',
            name='customers',
        ),
        migrations.AddField(
            model_name='bulknotification',
            name='receivers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
