# Generated by Django 6.0.2 on 2026-03-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bulknotification_receivers_remove_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='role',
        ),
    ]
