# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_combo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrawmaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_mapping/'),
        ),
    ]
