# Generated by Django 6.0.2 on 2026-03-06 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_vendor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='core.vendor'),
        ),
    ]
