# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_recipe_mapping_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='raw_materials/'),
        ),
    ]
