# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_raw_material_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
