# Generated by Django 6.0.2

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_table_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='default_service_charge',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal('0'),
                help_text='Default service charge applied to every order for this restaurant.',
                max_digits=12,
                null=True,
            ),
        ),
    ]
