# Generated by Django 6.0.2 on 2026-02-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_service_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
