# Generated by Django 6.0.2 on 2026-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_restaurant_default_service_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('table', 'Table'), ('packing', 'Packing'), ('delivery', 'Delivery')], default='table', max_length=20),
        ),
    ]
