# Generated by Django 6.0.2 on 2026-03-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='receive_updates',
            field=models.BooleanField(default=True),
        ),
    ]
