# Generated by Django 6.0.2 on 2026-02-24 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='assigned_tables',
            field=models.ManyToManyField(blank=True, related_name='assigned_waiters', to='core.table'),
        ),
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(blank=True, max_length=64)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_calls', to='core.staff')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_calls', to='core.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_calls', to='core.table')),
            ],
            options={
                'db_table': 'core_waiter_call',
                'ordering': ['-created_at'],
            },
        ),
    ]
