# Generated by Django 6.0.2 on 2026-02-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_waiter_call_and_staff_assigned_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('running', 'Running'), ('ready', 'Ready'), ('served', 'Served'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
