# Generated by Django 6.0.2 on 2026-02-25 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_help_support_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Customer delivery location latitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lon',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Customer delivery location longitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Pickup point for delivery', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Pickup point for delivery', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('last_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('in_house', 'In House'), ('pathao', 'Pathao'), ('yango', 'Yango')], default='in_house', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_rider',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='delivery', serialize=False, to='core.order')),
                ('delivery_status', models.CharField(choices=[('accepted', 'Accepted'), ('rider_assigned', 'Rider Assigned'), ('rider_picked_up', 'Rider Picked Up'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='accepted', max_length=20)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pickup_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('delivery_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rider_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rider_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('third_party_request_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.rider')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'db_table': 'core_delivery',
            },
        ),
    ]
