# Generated by Django 6.0.2 on 2026-02-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delivery_rider_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
