# Generated by Django 6.0.2 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_user_is_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
