# Generated by Django 6.0.2 on 2026-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_table_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Order-level discount amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='Online payment transaction ID (e.g. Esewa)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='esewa_merchant_id',
            field=models.CharField(blank=True, help_text='Esewa merchant ID for online payment QR', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
