# Generated by Django 6.0.2 on 2026-02-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_esewa_transaction_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax percentage applied on subtotal for invoice (e.g. 13 for 13%%)', max_digits=5, null=True),
        ),
    ]
