# Generated by Django 6.0.2

from django.db import migrations, models


def backfill_country_code(apps, schema_editor):
    """Set country_code to '+91' where empty for User and Customer."""
    User = apps.get_model('core', 'User')
    Customer = apps.get_model('core', 'Customer')
    default_cc = '+91'
    User.objects.filter(country_code='').update(country_code=default_cc)
    User.objects.filter(country_code__isnull=True).update(country_code=default_cc)
    Customer.objects.filter(country_code='').update(country_code=default_cc)
    Customer.objects.filter(country_code__isnull=True).update(country_code=default_cc)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_in_app_notification'),
    ]

    operations = [
        migrations.RunPython(backfill_country_code, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                fields=('country_code', 'phone'),
                name='unique_user_country_phone',
            ),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(
                fields=('country_code', 'phone'),
                name='unique_customer_country_phone',
            ),
        ),
    ]
