# Generated by Django 6.0.2 on 2026-02-27 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_country_code_required_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary_type',
            field=models.CharField(choices=[('per_day', 'Per Day'), ('monthly', 'Monthly')], default='per_day', max_length=20),
        ),
    ]
