# Generated by Django (data migration to normalize country codes)

from django.db import migrations


def normalize_country_codes_forward(apps, schema_editor):
    """Set country_code to '91' where '+91', and '977' where '+977' for User, Customer, Restaurant, Vendor."""
    User = apps.get_model('core', 'User')
    Customer = apps.get_model('core', 'Customer')
    Restaurant = apps.get_model('core', 'Restaurant')
    Vendor = apps.get_model('core', 'Vendor')
    User.objects.filter(country_code='+91').update(country_code='91')
    User.objects.filter(country_code='+977').update(country_code='977')
    Customer.objects.filter(country_code='+91').update(country_code='91')
    Customer.objects.filter(country_code='+977').update(country_code='977')
    Restaurant.objects.filter(country_code='+91').update(country_code='91')
    Restaurant.objects.filter(country_code='+977').update(country_code='977')
    Vendor.objects.filter(country_code='+91').update(country_code='91')
    Vendor.objects.filter(country_code='+977').update(country_code='977')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_attendance_salary_type_created_by'),
    ]

    operations = [
        migrations.RunPython(normalize_country_codes_forward, noop),
    ]
