# Generated by Django 6.0.2 on 2026-02-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_normalize_country_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_restaurant',
            field=models.BooleanField(default=True),
        ),
    ]
