# Generated by Django 6.0.2 on 2026-02-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_restaurant_is_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='order',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='rider',
        ),
        migrations.DeleteModel(
            name='HelpSupportEntry',
        ),
        migrations.RemoveField(
            model_name='inappnotification',
            name='recipient_customer',
        ),
        migrations.RemoveField(
            model_name='inappnotification',
            name='recipient_user',
        ),
        migrations.RemoveField(
            model_name='inappnotification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='user',
        ),
        migrations.RemoveField(
            model_name='waitercall',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='waitercall',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='waitercall',
            name='table',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_lon',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('table', 'Table'), ('packing', 'Packing')], default='table', max_length=20),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='InAppNotification',
        ),
        migrations.DeleteModel(
            name='Rider',
        ),
        migrations.DeleteModel(
            name='WaiterCall',
        ),
    ]
