from django.urls import path
from . import auth_views
from . import views

urlpatterns = [
    path('auth/login/', auth_views.login),
    path('auth/register/', auth_views.register),
    path('auth/me/', auth_views.me),
    path('auth/logout/', auth_views.logout),
    path('auth/forgot-password/request-otp/', auth_views.forgot_password_request_otp),
    path('auth/forgot-password/verify-otp/', auth_views.forgot_password_verify_otp),
    path('auth/forgot-password/set-password/', auth_views.forgot_password_set_password),
    # Owner (scoped dashboard and lists)
    path('owner/dashboard-stats/', views.owner_dashboard_stats),
    path('owner/my-restaurant/', views.owner_my_restaurant),
    path('owner/staff/', views.owner_staff_list),
    path('owner/staff/stats/', views.owner_staff_stats),
    path('owner/staff/available-users/', views.owner_staff_available_users),
    path('owner/staff/<int:pk>/', views.owner_staff_detail),
    path('owner/attendance/stats/', views.owner_attendance_stats),
    path('owner/attendance/my/', views.owner_attendance_my_list),
    path('owner/attendance/', views.owner_attendance_list),
    path('owner/attendance/<int:pk>/', views.owner_attendance_detail),
    path('owner/feedback/stats/', views.owner_feedback_stats),
    path('owner/feedback/', views.owner_feedback_list),
    path('owner/feedback/<int:pk>/', views.owner_feedback_detail),
    path('owner/customers/', views.owner_customers_list),
    path('owner/customers/stats/', views.owner_customers_stats),
    path('owner/vendors/', views.owner_vendors_list),
    path('owner/vendors/stats/', views.owner_vendors_stats),
    path('owner/vendors/<int:pk>/', views.owner_vendor_detail),
    path('owner/paid-records/stats/', views.owner_paid_records_stats),
    path('owner/paid-records/', views.owner_paid_records_list),
    path('owner/received-records/stats/', views.owner_received_records_stats),
    path('owner/received-records/', views.owner_received_records_list),
    path('owner/payroll/', views.owner_payroll_list),
    path('owner/performance/', views.owner_performance),
    path('owner/reports/staff/', views.owner_report_staff),
    path('owner/reports/finance/', views.owner_report_finance),
    path('owner/reports/credits/', views.owner_report_credits),
    path('owner/reports/customers/', views.owner_report_customers),
    path('owner/reports/products/', views.owner_report_products),
    path('owner/reports/inventory/', views.owner_report_inventory),
    path('owner/reports/pl/', views.owner_report_pl),
    path('owner/reports/orders/', views.owner_report_orders),
    path('owner/reports/vendors/', views.owner_report_vendors),
    path('owner/analytics/overview/', views.owner_analytics_overview),
    path('owner/analytics/comparison/', views.owner_analytics_comparison),
    path('owner/analytics/restaurant/<int:restaurant_id>/', views.owner_analytics_restaurant),
    # Units (owner/manager)
    path('units/', views.units_list),
    path('units/<int:pk>/', views.unit_detail),
    # Categories (owner/manager)
    path('categories/', views.categories_list),
    path('categories/<int:pk>/', views.category_detail),
    # Raw materials (owner/manager)
    path('raw-materials/stats/', views.raw_materials_stats),
    path('raw-materials/<int:pk>/', views.raw_material_detail),
    path('raw-materials/', views.raw_materials_list),
    # Tables (owner/manager)
    path('tables/stats/', views.tables_stats),
    path('tables/<int:pk>/', views.table_detail),
    path('tables/', views.tables_list),
    # Purchases (owner/manager)
    path('purchases/stats/', views.purchases_stats),
    path('purchases/<int:pk>/', views.purchase_detail),
    path('purchases/', views.purchases_list),
    # Orders (owner/manager)
    path('orders/stats/', views.orders_stats),
    path('orders/', views.orders_list),
    path('orders/<int:pk>/', views.order_detail),
    # Expenses (owner/manager)
    path('expenses/stats/', views.expenses_stats),
    path('expenses/', views.expenses_list),
    path('expenses/<int:pk>/', views.expense_detail),
    # Products (owner/manager)
    path('products/', views.products_list),
    path('products/<int:pk>/', views.product_detail),
    # Combos (owner/manager)
    path('combos/', views.combos_list),
    path('combos/<int:pk>/', views.combo_detail),
    # Super admin: Owners
    path('owners/stats/', views.owner_stats),
    path('owners/analytics/', views.owner_analytics),
    path('owners/search/', views.owner_search),
    path('owners/', views.owner_list),
    path('owners/<int:pk>/', views.owner_detail),
    # Restaurants (super admin)
    path('restaurants/stats/', views.restaurant_stats),
    path('restaurants/analytics/', views.restaurant_analytics),
    path('restaurants/', views.restaurant_list),
    path('restaurants/<int:pk>/pay-due/', views.restaurant_pay_due),
    path('restaurants/<int:pk>/', views.restaurant_detail),
    # Due (super admin)
    path('due/stats/', views.due_stats),
    # KYC (super admin)
    path('kyc/stats/', views.kyc_stats),
    path('kyc/', views.kyc_list),
    # Shareholders (super admin)
    path('shareholders/stats/', views.shareholder_stats),
    path('shareholders/analytics/', views.shareholder_analytics),
    path('shareholders/search/', views.shareholder_search),
    path('shareholders/withdrawal-history/', views.shareholder_withdrawal_history),
    path('shareholders/withdrawals/stats/', views.shareholder_withdrawal_stats),
    path('shareholders/withdrawals/analytics/', views.shareholder_withdrawal_analytics),
    path('shareholders/withdrawals/', views.shareholder_withdrawal_list),
    path('shareholders/withdrawals/<int:pk>/', views.shareholder_withdrawal_detail),
    path('shareholders/', views.shareholder_list),
    path('shareholders/<int:pk>/', views.shareholder_detail),
    # Transactions (super admin)
    path('transactions/stats/', views.transaction_stats),
    path('transactions/', views.transaction_list),
    path('transactions/<int:pk>/', views.transaction_detail),
    # Super Settings (super admin)
    path('super-settings/overview/', views.super_settings_overview),
    path('super-settings/dashboard-stats/', views.super_settings_dashboard_stats),
    path('super-settings/fee-income/', views.super_settings_fee_income),
    path('super-settings/', views.super_setting_detail),
    # QR Stand Orders (super admin)
    path('qr-orders/price/', views.qr_stand_order_price),
    path('qr-orders/stats/', views.qr_stand_order_stats),
    path('qr-orders/analytics/', views.qr_stand_order_analytics),
    path('qr-orders/', views.qr_stand_order_list),
    path('qr-orders/<int:pk>/', views.qr_stand_order_detail),
    path('qr-orders/<int:pk>/pay/', views.qr_stand_order_pay),
    # Notifications (super admin)
    path('notifications/stats/', views.notification_stats),
    path('notifications/', views.notification_list),
    path('notifications/<int:pk>/', views.notification_detail),
    path('notifications/<int:pk>/send/', views.notification_send),
    # Public (no auth)
    path('public/menu/<slug:slug>/', views.public_menu_by_slug),
    path('public/restaurant/<slug:slug>/order/', views.public_order_create),
    # Customers (super admin, for receiver picker)
    path('customers/', views.customer_list),
    # Customer-scoped API (logged-in customer only)
    path('customer/dashboard-stats/', views.customer_dashboard_stats),
    path('customer/me/', views.customer_me),
    path('customer/restaurants/', views.customer_restaurants_list),
    path('customer/restaurants/<int:pk>/', views.customer_restaurant_detail),
    path('customer/restaurants/<int:pk>/tables/', views.customer_restaurant_tables),
    path('customer/orders/', views.customer_orders_list),
    path('customer/orders/<int:pk>/', views.customer_order_detail),
    path('customer/transactions/', views.customer_transactions_list),
    path('customer/transactions/analytics/', views.customer_transactions_analytics),
    path('customer/transactions/<int:pk>/', views.customer_transaction_detail),
    path('customer/credits/', views.customer_credits_list),
    path('customer/feedback/', views.customer_feedback_list),
    path('customer/feedback/<int:pk>/', views.customer_feedback_detail),
]
